import Head from 'next/head'
import styles from '../styles/Home.module.css'
import RefreshAllButton from '../components/RefreshButton/RefreshButton'
import AvatarTile from '../components/AvatarTile/AvatarTile'
import AddButton from '../components/AddButton/AddButton'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> 21-csr-ssr-ssg-nextjs </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <AddButton />
        <RefreshAllButton />

      </main>
    </div>
  )
}
