import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lecture 21 - CSR - SSR - SSG - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </div>
  );
}
