import Head from 'next/head';
import { React, useState } from 'react';
import RefreshAllButton from '../components/RefreshAllButton/RefreshAllButton.jsx';
import AddButton from '../components/AddButton/AddButton.jsx';
import AvatarCard from '../components/AvatarCard/AvatarCard.jsx';

const URL = 'https://tinyfac.es/api/data?limit=1&quality=0';

export default function Home() {
  const [avatars, setAvatars] = useState([]);

  function getAvatar() {
    return fetch(URL)
      .then((res) => {
        if (res.ok) {
          return res.json();
        }
        throw new Error('Something went wrong please try again later');
      })
      .then((dataJson) => {
        return dataJson[0].url;
      })
      .catch((err) => {
        console.log(err);
        return '/images/fetchErrorImg.svg';
      });
  }

  async function addAvatar() {
    const newAvatar = await getAvatar();
    const newList = [...avatars, newAvatar];
    setAvatars(newList);
  }

  async function refreshClickedAvatar(avatarId) {
    const newAvatar = await getAvatar();
    let newList = avatars.map((avatar, index) => {
      if (index === avatarId) {
        return newAvatar;
      }
      return avatar;
    });
    setAvatars(newList);
  }

  async function refreshAllAvatars() {
    let newList = await Promise.all(
      avatars.map(() => {
        return getAvatar();
      }),
    );
    setAvatars(newList);
  }

  return (
    <>
      <Head>
        <title> 21-csr-ssr-ssg-nextjs </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="App">
        <div className="cards-container">
          {avatars.map((avatar, index) => {
            return <AvatarCard key={index} avatarImg={avatar} onClick={() => refreshClickedAvatar(index)} />;
          })}
          <AddButton onClick={addAvatar} />
        </div>
        <RefreshAllButton onClick={refreshAllAvatars} />
      </main>
    </>
  );
}
