import './scss/style.scss'
import './scss/layout.scss'
import './scss/media.scss'
import './images/photo.png'
import './images/icons/youtube-icon.svg'
import './images/icons/linkedIn-icon.svg'
import './images/icons/dark-light-theme-icon.svg'
import './images/icons/github-icon.svg'
import './images/icons/twitter-icon.svg'
import './images/icons/download-icon.svg'
import './images/rectangle-1.png'
import './images/rectangle-2.png'
import './images/rectangle-3.png'
import './images/rectangle-4.png'
import './images/rectangle-5.png'
import './images/rectangle-6.png'

